### ISSUE TITLE
transformer.js:32 Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by MeterKishor** [hilkeheremans/redux-persist-seamless-immutable#17]
Hello, I'm getting  following error. how can i fix it? Thanks!
Config:
const transformerConfig = {
  whitelistPerReducer: {
    
  },
  blacklistPerReducer: {
    
  }
}

Error:
transformer.js:32 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at transformer.js:32:1
    at Object._in [as in] (createTransform.js:16:1)
    at createPersistoid.js:66:1
    at Array.reduce (<anonymous>)
    at processNextKey (createPersistoid.js:65:1)

**Comment by MeterKishor** [comment]
found solution in https://github.com/telesoft-parksmart/redux-persist-seamless-immutable
